spring.application.name=api_wayfinder
# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/wayfinder_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate y PostGIS
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Puerto del servidor
server.port=8080